Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/878abe5e-9093-4c9f-8568-a74604982d5a
(17,)
17
ERROR 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/101f191b-6918-4d6a-be53-a44f89cf0f65
(17,)
17
ERROR 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/bf2080d6-c8ba-4514-89ca-e3c499dca6eb
(17,)
17
ERROR 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/f8371811-0863-4d82-85af-5104e030f5e9
(17,)
17
ERROR 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/8eb7be4d-40cd-418e-b2af-12d7bc3e7ef3
(17,)
17
ERROR 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/324625e6-d05c-4de2-b2ea-8bdb15245e23
(17,)
17
ERROR 'tuple' object is not callable
Process Process-21:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Process Process-22:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Process Process-19:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/13bef668-19cf-4606-9fd4-7d186eb5b792
(17,)
17
ERROR 'tuple' object is not callable
Process Process-24:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/d9128c2b-29be-4e0d-ae0b-ee767b813e68
(17,)
17
ERROR 'tuple' object is not callable
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/e6cf5c11-1acd-4fb8-8626-c74e07ab26d7
(17,)
17
ERROR 'tuple' object is not callable
Process Process-17:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/5ece0423-3610-4f28-9f64-8d8c22f6675c
(17,)
17
ERROR 'tuple' object is not callable
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/09f81e1a-4ede-48a2-b7ac-5c70ed758775
(17,)
17
ERROR 'tuple' object is not callable
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/dce4695c-ee5d-46e2-b7da-864d44fa1255
(17,)
17
ERROR 'tuple' object is not callable
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/351cb22b-212a-4081-a225-0355de0870ef
(17,)
17
ERROR 'tuple' object is not callable
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/e3c63ba5-7be4-4b67-8bea-2415002f5d68
(17,)
17
ERROR 'tuple' object is not callable
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/59cef9a4-c04b-4627-93dd-f5f80d23bbc9
(17,)
17
ERROR 'tuple' object is not callable
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/1c742aa6-3923-4285-b5c7-1d1da3880819
(17,)
17
ERROR 'tuple' object is not callable
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/f215f2ae-1b55-4dfc-a7e8-56eaf56c47f4
(17,)
17
ERROR 'tuple' object is not callable
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/934c5b3d-e05c-4db4-bfd4-02f59f849d89
(17,)
17
ERROR 'tuple' object is not callable
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/28d1507b-b421-4224-ad86-a711223bdaf5
(17,)
17
ERROR 'tuple' object is not callable
Process Process-23:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/2886cbbd-2944-441d-af03-be4d41d7fb6b
(17,)
17
ERROR 'tuple' object is not callable
Process Process-20:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/d7fc1726-1b63-4ea7-87eb-b087ccc56279
(17,)
17
ERROR 'tuple' object is not callable
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/ede34f51-8d9c-4bb3-810c-c4f4a85c1b48
(17,)
17
ERROR 'tuple' object is not callable
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/feac66f5-0a92-48c9-b7df-8f9ff62ca4c4
(17,)
17
ERROR 'tuple' object is not callable
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
Logging in: /home/eecs/chloehsu/ppo_ablation/code-for-paper/src/reward_scaling/agents/c9e558c5-dc61-43e1-9c8e-8dee0aa911bf
(17,)
17
ERROR 'tuple' object is not callable
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_agents.py", line 20, in run_single_config
    raise e
  File "run_agents.py", line 17, in run_single_config
    main(params)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/run.py", line 119, in main
    mean_reward = p.train_step()
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 496, in train_step
    saps, avg_ep_reward, avg_ep_length = self.collect_saps(num_saps)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 345, in collect_saps
    should_tqdm=should_tqdm)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 286, in run_trajectories
    ret = self.multi_actor_step(next_actions, envs)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/agent.py", line 211, in multi_actor_step
    new_state, normed_reward, is_done, info = env.step(gym_action)
  File "/home/eecs/chloehsu/ppo_ablation/code-for-paper/src/policy_gradients/custom_env.py", line 68, in step
    print(state.shape())
TypeError: 'tuple' object is not callable
